version: 2
updates:
  # npm i rot
  - package-ecosystem: npm
    directory: "/"
    schedule: { interval: daily }
    allow: [{ dependency-type: all }]
    labels: ["dependencies", "automated"]
    assignees: ["team-backend"]
    reviewers: ["security-champions"]
    open-pull-requests-limit: 50
    rebase-strategy: auto
    commit-message:
      prefix: "deps"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    groups:                           # färre men mer meningsfulla PR:ar
      minor-and-patch:
        update-types: ["minor", "patch"]
      dev-deps:
        dependency-type: "development"
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule: { interval: daily }
  # Python i /service
  - package-ecosystem: pip
    directory: "/service"
    schedule: { interval: daily }
