site_name: Architecture as Code at aac.geon.se
site_description: "Architecture as Code book content published as a browsable documentation site."
site_url: https://aac.geon.se/
repo_url: https://github.com/geonitab/architecture_as_code
repo_name: architecture_as_code
nav:
  - Overview:
      - Welcome: index.md
      - Book Structure: book_structure.md
      - Documentation and Architecture Contribution Workflow: documentation_workflow.md
  - Part A – Foundations:
      - index: part_a_foundations.md
      - Introduction to Architecture as Code: 01_introduction.md
      - Fundamental Principles of Architecture as Code: 02_fundamental_principles.md
      - Version Control and Code Structure: 03_version_control.md
      - Architecture Decision Records (ADR): 04_adr.md
  - Part B – Architecture Platform:
      - index: part_b_platform.md
      - Automation, DevOps and CI/CD for Infrastructure as Code: 05_automation_devops_cicd.md
      - "Structurizr: Architecture Modelling as Code": 06_structurizr.md
      - Containerisation and Orchestration as Code: 07_containerisation.md
      - Microservices Architecture as Code: 08_microservices.md
  - Part C – Security & Governance:
      - index: part_c_security.md
      - Security Fundamentals for Architecture as Code: 09_security_fundamentals.md
      - Advanced Security Patterns and Implementation: 09b_security_patterns.md
      - Risk and Threat Modelling as Code: 09c_risk_and_threat_as_code.md
      - Policy and Security as Code in Detail: 10_policy_and_security.md
      - Governance as Code: 11_governance_as_code.md
      - Compliance and Regulatory Adherence: 12_compliance.md
  - Part D – Delivery & Operations:
      - index: part_d_delivery.md
      - Testing Strategies for Infrastructure as Code: 13_testing_strategies.md
      - Architecture as Code in Practice: 14_practical_implementation.md
      - Evidence as Code and Continuous Assurance: 15_evidence_as_code.md
      - Cost Optimisation and Resource Management: 15_cost_optimization.md
      - Migration from Traditional Infrastructure: 16_migration.md
  - Part E – Organisation & Leadership:
      - index: part_e_leadership.md
      - Organisational Change and Team Structures: 17_organisational_change.md
      - Team Structure and Competency Development for IaC: 18_team_structure.md
      - Management as Code: 19_management_as_code.md
      - AI Agent Team for Architecture as Code Initiatives: 20_ai_agent_team.md
      - Digitalisation through Code-based Infrastructure: 21_digitalisation.md
  - Part F – Experience & Best Practices:
      - index: part_f_practices.md
      - Documentation as Code vs Architecture as Code: 22_documentation_vs_architecture.md
      - Interplay Between Soft-As-Code Disciplines: 23_soft_as_code_interplay.md
      - Best Practices and Lessons Learned: 24_best_practices.md
  - Part G – Future & Wrap-up:
      - index: part_g_future.md
      - Future Trends in Architecture as Code: 25_future_trends.md
      - Prerequisites for Architecture as Code Adoption: 26a_prerequisites_for_aac.md
      - Anti-Patterns in Architecture as Code Programmes: 26b_aac_anti_patterns.md
      - Conclusion: 27_conclusion.md
  - Appendices:
      - Part H – Appendices and Reference Overview: part_h_appendices.md
      - Glossary: glossary.md
      - About the Author: about_the_author.md
      - Appendix A – Code Examples and Technical Implementations: 30_appendix_code_examples.md
      - Appendix B – Technical Architecture for Book Production: appendix_b_technical_architecture.md
      - Appendix C – FINOS Project Blueprint: 32_finos_project_blueprint.md
      - Appendix D – Architecture as Code Maturity Model: architecture_as_code_maturity_model.md
      - Appendix E – Architecture as Code Maturity Radar Tool: maturity_model_radar.html
      - References and Sources: 33_references.md
      - Appendix F – Control Mapping Matrix Template: 34_control_mapping_matrix_template.md
  - Prezi Deck: prezi/index.html
docs_dir: docs
use_directory_urls: true
theme:
  name: readthedocs
markdown_extensions:
  - toc
  - tables
extra_css:
  - stylesheets/code-dark.css
extra_javascript:
  - javascripts/mermaid-init.js
