---
config:
  theme: 'base'
  themeVariables:
    primaryColor: '#BB2528'
    primaryTextColor: '#fff'
    primaryBorderColor: '#7C0000'
    lineColor: '#F8B229'
    secondaryColor: '#006100'
    tertiaryColor: '#fff'
---
graph LR
    A[Requirements as Code] --> B[Compliance as Code]
    B --> C[Documentation as Code]
    C --> D[Design as Code]
    D --> E[Coding]
    E --> F[CI/CD]
    F --> G[Infrastructure as Code]
    
    D -.-> H[Design Tokens]
    H -.-> E
    
    G -.-> A
    F -.-> B
