---
config:
  theme: 'base'
  themeVariables:
    primaryColor: '#BB2528'
    primaryTextColor: '#fff'
    primaryBorderColor: '#7C0000'
    lineColor: '#F8B229'
    secondaryColor: '#006100'
    tertiaryColor: '#fff'
---
graph LR
    A[Traditionella Silos] --> B[Cross-funktionella Team]
    B --> C[DevOps Kultur]
    C --> D[Continuous Learning]
    D --> E[High Performance]