---
config:
  theme: 'base'
  themeVariables:
    primaryColor: '#BB2528'
    primaryTextColor: '#fff'
    primaryBorderColor: '#7C0000'
    lineColor: '#F8B229'
    secondaryColor: '#006100'
    tertiaryColor: '#fff'
---
graph LR
    A[Traditionell arkitektur] --> B[Manuella processer]
    C[Architecture as Code] --> D[Automatiserade processer] 
    E[Infrastructure as Code] --> F[Praktiskt exempel]