graph TD
    PO[Projektägare] --> PM[Project Manager]
    PM --> ARCH[Architect]
    PM --> RA[Requirements Analyst]
    PM --> DES[Designer]
    PM --> DEV[Developer]
    PM --> QC[Quality Control]
    PM --> ED[Editor]
    PM --> GD[Graphic Designer]
    ARCH --> PM
    RA --> PM
    DES --> PM
    DEV --> PM
    QC --> PM
    ED --> PM
    GD --> PM
