---
config:
  theme: 'base'
  themeVariables:
    primaryColor: '#BB2528'
    primaryTextColor: '#fff'
    primaryBorderColor: '#7C0000'
    lineColor: '#F8B229'
    secondaryColor: '#006100'
    tertiaryColor: '#fff'
---
graph LR
    A[Praktisk erfarenhet] --> B[Lärande från misslyckanden]
    B --> C[Anpassning av praktiker]
    C --> D[Mognadsutveckling]
    D --> E[Förbättrad automation]
    E --> A