---
config:
  theme: 'base'
  themeVariables:
    primaryColor: '#BB2528'
    primaryTextColor: '#fff'
    primaryBorderColor: '#7C0000'
    lineColor: '#F8B229'
    secondaryColor: '#006100'
    tertiaryColor: '#fff'
---
graph LR
    A[Security policies] --> B[Secret management]
    B --> C[Access control]
    C --> D[Compliance scanning]
    D --> E[Threat modeling]