mindmap
  root((Threat Modeling))
    Threat Landscape
      Supply Chain Attacks
      Code Injection
      Insider Threats
      Infrastructure Exploits
    STRIDE Methodology
      Spoofing
      Tampering
      Repudiation
      Information Disclosure
      Denial of Service
      Elevation of Privilege
