name: Editor Agent

on:
  workflow_dispatch:
    inputs:
      objective:
        description: "Vilken dokumentationsuppgift ska slutföras?"
        required: true
      documentation_scope:
        description: "Vilka dokument, sektioner eller format ska uppdateras?"
        required: false
        default: ""
      style_notes:
        description: "Riktlinjer, språknoteringar eller källor som måste följas"
        required: false
        default: ""
  workflow_call:
    inputs:
      objective:
        required: true
        type: string
      documentation_scope:
        required: false
        type: string
        default: ""
      style_notes:
        required: false
        type: string
        default: ""
    outputs:
      plan:
        description: "Editor-agentens plan"
        value: ${{ jobs.plan.outputs.plan }}

jobs:
  plan:
    name: Sammanställ dokumentationsplan
    runs-on: ubuntu-latest
    outputs:
      plan: ${{ steps.compose.outputs.plan }}
    steps:
      - name: Komponera plan
        id: compose
        env:
          OBJECTIVE: ${{ inputs.objective }}
          DOCUMENTATION_SCOPE: ${{ inputs.documentation_scope }}
          STYLE_NOTES: ${{ inputs.style_notes }}
        run: |
          set -euo pipefail
          objective="${OBJECTIVE:-Ingen specifik målsättning angiven.}"
          scope_value="${DOCUMENTATION_SCOPE:-}"
          if [ -z "$scope_value" ]; then
            scope_value="Inget dokumentationsomfång angivet."
          fi
          style_value="${STYLE_NOTES:-}"
          if [ -z "$style_value" ]; then
            style_value="Inga stil- eller språknoter angivna."
          fi

          export AGENT_OBJECTIVE="$objective"
          export AGENT_SCOPE="$scope_value"
          export AGENT_STYLE="$style_value"

          summary=$(
            cat <<'PLAN' | envsubst
# Editor-agentens plan

## Mål
$AGENT_OBJECTIVE

## Dokumentationsomfång
$AGENT_SCOPE

## Stil- och språknoter
$AGENT_STYLE

## Primära ansvar enligt 28_ai_agent_team.md
- Skapa och uppdatera dokumentation i docs/ och relaterade filer.
- Säkerställa struktur, språkstandard och versionsspårning.
- Synkronisera med Requirements Analyst och Designer för uppdaterade beslut.
- Sammanställa sprintanteckningar och kunskapsmaterial.

## Rekommenderad arbetsgång
1. Inventera befintliga dokument och identifiera vad som behöver ändras.
2. Uppdatera innehåll enligt riktlinjer och spåra ändringar i changelog.
3. Verifiera att dokumentationen speglar senaste krav, design och implementering.
4. Koordinera med Graphic Designer om visualiseringar behöver uppdateras.
5. Leverera publiceringsredo material och meddela Project Manager.

## Leverabler
- Uppdaterade dokument med versionsnoteringar.
- Kommunikationsunderlag eller release-notiser till projektägaren.
- Lista över eventuella uppföljningsaktiviteter eller saknade källor.

## Kontrollpunkter
- Säkerställ språkgranskning och konsekvent terminologi.
- Håll docs/README.md uppdaterad med senaste ändringar.
- Bekräfta att QA- och kravartefakter refereras korrekt.
PLAN
          )

          printf '%s\n' "$summary"
          printf '%s\n' "$summary" >> "$GITHUB_STEP_SUMMARY"
          {
            echo "plan<<EOF"
            printf '%s\n' "$summary"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
