name: Graphic Designer Agent

on:
  workflow_dispatch:
    inputs:
      objective:
        description: "Which graphic deliverable should be produced?"
        required: true
      visual_scope:
        description: "Which diagrams, illustrations, or media should be produced?"
        required: false
        default: ""
      asset_requests:
        description: "Requested formats, ready-made templates, or brand requirements"
        required: false
        default: ""
  workflow_call:
    inputs:
      objective:
        required: true
        type: string
      visual_scope:
        required: false
        type: string
        default: ""
      asset_requests:
        required: false
        type: string
        default: ""
    outputs:
      plan:
        description: "Graphic Designer plan"
        value: ${{ jobs.plan.outputs.plan }}

jobs:
  plan:
    name: Compile graphic plan
    runs-on: ubuntu-latest
    outputs:
      plan: ${{ steps.compose.outputs.plan }}
    steps:
      - name: Compose plan
        id: compose
        env:
          OBJECTIVE: ${{ inputs.objective }}
          VISUAL_SCOPE: ${{ inputs.visual_scope }}
          ASSET_REQUESTS: ${{ inputs.asset_requests }}
        run: |
          set -euo pipefail
          objective="${OBJECTIVE:-No specific objective provided.}"
          scope_value="${VISUAL_SCOPE:-}"
          if [ -z "$scope_value" ]; then
            scope_value="No visual scope provided."
          fi
          asset_value="${ASSET_REQUESTS:-}"
          if [ -z "$asset_value" ]; then
            asset_value="No specific format or template requests provided."
          fi

          export AGENT_OBJECTIVE="$objective"
          export AGENT_SCOPE="$scope_value"
          export AGENT_ASSETS="$asset_value"

          summary=$(
            cat <<PLAN
# Graphic Designer plan

## Objectives
$AGENT_OBJECTIVE

## Visual scope
$AGENT_SCOPE

## Requested assets and formats
$AGENT_ASSETS

## Primary responsibilities from 28_ai_agent_team.md
- Produce visual diagrams and illustrations for architecture and processes.
- Ensure visualizations are accurate and integrated into documentation.
- Maintain a library of graphic components and themes.
- Create quick sketches to support the Designer and Developer.

## Recommended workflow
1. Confirm delivery goals and target audience with the Project Manager and Architect.
2. Gather necessary source data from the Architect, Designer, and Editor.
3. Create or update diagrams using the agreed style (Mermaid/PlantUML/Illustrator).
4. Perform quality checks against brand guidelines and technical requirements.
5. Deliver files and links to the Editor and document version information.

## Deliverables
- Updated diagrams or visual assets according to the scope.
- Exports in requested formats (SVG/PNG/PDF) and source files.
- Version log and recommendations for further iterations.

## Checkpoints
- Verify that the visuals map back to architecture and requirements decisions.
- Ensure accessibility and contrast requirements are met.
- Communicate blockers or the need for additional data.
PLAN
          )

          printf '%s\n' "$summary"
          printf '%s\n' "$summary" >> "$GITHUB_STEP_SUMMARY"
          {
            echo "plan<<EOF"
            printf '%s\n' "$summary"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
