name: Graphic Designer Agent

on:
  workflow_dispatch:
    inputs:
      objective:
        description: "Vilken grafisk leverans ska tas fram?"
        required: true
      visual_scope:
        description: "Vilka diagram, illustrationer eller media ska produceras?"
        required: false
        default: ""
      asset_requests:
        description: "Önskade format, färdiga mallar eller brand-krav"
        required: false
        default: ""
  workflow_call:
    inputs:
      objective:
        required: true
        type: string
      visual_scope:
        required: false
        type: string
        default: ""
      asset_requests:
        required: false
        type: string
        default: ""
    outputs:
      plan:
        description: "Graphic Designer-agentens plan"
        value: ${{ jobs.plan.outputs.plan }}

jobs:
  plan:
    name: Sammanställ grafisk plan
    runs-on: ubuntu-latest
    outputs:
      plan: ${{ steps.compose.outputs.plan }}
    steps:
      - name: Komponera plan
        id: compose
        env:
          OBJECTIVE: ${{ inputs.objective }}
          VISUAL_SCOPE: ${{ inputs.visual_scope }}
          ASSET_REQUESTS: ${{ inputs.asset_requests }}
        run: |
          set -euo pipefail
          objective="${OBJECTIVE:-Ingen specifik målsättning angiven.}"
          scope_value="${VISUAL_SCOPE:-}"
          if [ -z "$scope_value" ]; then
            scope_value="Inget visuellt scope angivet."
          fi
          asset_value="${ASSET_REQUESTS:-}"
          if [ -z "$asset_value" ]; then
            asset_value="Inga särskilda format- eller mallönskemål angivna."
          fi

          export AGENT_OBJECTIVE="$objective"
          export AGENT_SCOPE="$scope_value"
          export AGENT_ASSETS="$asset_value"

          summary=$(
            cat <<'PLAN' | envsubst
# Graphic Designer-agentens plan

## Mål
$AGENT_OBJECTIVE

## Visuellt scope
$AGENT_SCOPE

## Begärda tillgångar och format
$AGENT_ASSETS

## Primära ansvar enligt 28_ai_agent_team.md
- Producera visuella diagram och illustrationer för arkitektur och processer.
- Säkerställa att visualiseringar är korrekta och integrerade i dokumentation.
- Underhålla bibliotek av grafiska komponenter och teman.
- Ta fram snabbskisser som stöd för Designer och Developer.

## Rekommenderad arbetsgång
1. Bekräfta leveransmål och målgrupp med Project Manager och Architect.
2. Samla nödvändigt källdata från Architect, Designer och Editor.
3. Skapa eller uppdatera diagram med överenskommen stil (Mermaid/PlantUML/Illustrator).
4. Utföra kvalitetskontroll mot brand guidelines och tekniska krav.
5. Leverera filer och länkar till Editor samt dokumentera versionsinformation.

## Leverabler
- Uppdaterade diagram eller visuella resurser enligt scope.
- Exporter i önskade format (SVG/PNG/PDF) samt källfiler.
- Versionslogg och rekommendationer för vidare iterationer.

## Kontrollpunkter
- Verifiera att grafiken är spårbar till arkitektur- och kravbeslut.
- Säkerställ att tillgänglighets- och kontrastkrav uppfylls.
- Kommunicera eventuella blockerare eller behov av kompletterande data.
PLAN
          )

          printf '%s\n' "$summary"
          printf '%s\n' "$summary" >> "$GITHUB_STEP_SUMMARY"
          {
            echo "plan<<EOF"
            printf '%s\n' "$summary"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
