name: Designer Agent

on:
  workflow_dispatch:
    inputs:
      objective:
        description: "Which design task should be prioritized?"
        required: true
      design_brief:
        description: "Link or summary of requirements, user flows, or brand goals"
        required: false
        default: ""
      research_notes:
        description: "Insights from user tests, workshops, or previous iterations"
        required: false
        default: ""
  workflow_call:
    inputs:
      objective:
        required: true
        type: string
      design_brief:
        required: false
        type: string
        default: ""
      research_notes:
        required: false
        type: string
        default: ""
    outputs:
      plan:
        description: "Designer agent plan"
        value: ${{ jobs.plan.outputs.plan }}

jobs:
  plan:
    name: Compile design plan
    runs-on: ubuntu-latest
    outputs:
      plan: ${{ steps.compose.outputs.plan }}
    steps:
      - name: Compose plan
        id: compose
        env:
          OBJECTIVE: ${{ inputs.objective }}
          DESIGN_BRIEF: ${{ inputs.design_brief }}
          RESEARCH_NOTES: ${{ inputs.research_notes }}
        run: |
          set -euo pipefail
          objective="${OBJECTIVE:-No specific objective provided.}"
          brief_value="${DESIGN_BRIEF:-}"
          if [ -z "$brief_value" ]; then
            brief_value="No design brief provided."
          fi
          research_value="${RESEARCH_NOTES:-}"
          if [ -z "$research_value" ]; then
            research_value="No research notes provided."
          fi

          export AGENT_OBJECTIVE="$objective"
          export AGENT_BRIEF="$brief_value"
          export AGENT_RESEARCH="$research_value"

          summary=$(
            cat <<PLAN
# Designer agent plan

## Objectives
$AGENT_OBJECTIVE

## Design brief
$AGENT_BRIEF

## Research and inspiration notes
$AGENT_RESEARCH

## Primary responsibilities from 28_ai_agent_team.md
- Produce wireframes, sketches, and interaction flows.
- Ensure adherence to design and brand guidelines.
- Validate proposals together with the Developer and Quality Control.
- Document design decisions and the component library.

## Recommended workflow
1. Confirm user needs and KPIs together with the Requirements Analyst.
2. Create or update wireframes/prototypes based on the design brief.
3. Sync with the Architect on architectural impact and with the Developer on implementation feasibility.
4. Prepare materials for quality review and demos.
5. Update the design library and link new resources for the Editor.

## Deliverables
- Updated wireframes or prototypes.
- Documented interaction flows and component descriptions.
- Feedback list and recommended next iterations.

## Checkpoints
- Align with brand and accessibility requirements.
- Ensure the design covers prioritized user stories.
- Communicate dependencies and decisions to the Project Manager.
PLAN
          )

          printf '%s\n' "$summary"
          printf '%s\n' "$summary" >> "$GITHUB_STEP_SUMMARY"
          {
            echo "plan<<EOF"
            printf '%s\n' "$summary"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
