name: Project Manager Agent

on:
  workflow_dispatch:
    inputs:
      objective:
        description: "Vilket mål ska Project Manager-agenten fokusera på?"
        required: true
      sprint_context:
        description: "Ytterligare kontext, länkar eller hinder som påverkar sprinten"
        required: false
        default: ""
      backlog_updates:
        description: "Lista över nya eller uppdaterade backloggposter"
        required: false
        default: ""
  workflow_call:
    inputs:
      objective:
        required: true
        type: string
      sprint_context:
        required: false
        type: string
        default: ""
      backlog_updates:
        required: false
        type: string
        default: ""
    outputs:
      plan:
        description: "Sammanfattning av Project Manager-agentens plan"
        value: ${{ jobs.plan.outputs.plan }}

jobs:
  plan:
    name: Sammanställ Project Manager-plan
    runs-on: ubuntu-latest
    outputs:
      plan: ${{ steps.compose.outputs.plan }}
    steps:
      - name: Komponera plan
        id: compose
        env:
          OBJECTIVE: ${{ inputs.objective }}
          SPRINT_CONTEXT: ${{ inputs.sprint_context }}
          BACKLOG_UPDATES: ${{ inputs.backlog_updates }}
        run: |
          set -euo pipefail
          objective="${OBJECTIVE:-Ingen specifik målsättning angiven.}"
          context_value="${SPRINT_CONTEXT:-}"
          if [ -z "$context_value" ]; then
            context_value="Ingen ytterligare kontext angiven."
          fi
          backlog_value="${BACKLOG_UPDATES:-}"
          if [ -z "$backlog_value" ]; then
            backlog_value="Inga backlogguppdateringar angivna."
          fi

          export AGENT_OBJECTIVE="$objective"
          export AGENT_CONTEXT="$context_value"
          export AGENT_BACKLOG="$backlog_value"

          summary=$(
            cat <<PLAN
# Project Manager-agentens plan

## Mål
$AGENT_OBJECTIVE

## Kontext
$AGENT_CONTEXT

## Backlogguppdateringar
$AGENT_BACKLOG

## Primära ansvar enligt 28_ai_agent_team.md
- Översätt projektägarens direktiv till sprintmål och uppgifter.
- Prioritera backloggen och synkronisera specialistrollerna.
- Hålla dagliga synkar och eskalera blockerare.
- Konsolidera status, risker och rekommendationer till projektägaren.

## Rekommenderad arbetsgång
1. Bekräfta sprintmål och definiera accepterade leveranser.
2. Koordinera beroenden mellan Architect, Requirements Analyst, Designer och Developer.
3. Säkerställ att Quality Control och Editor har planerade kvalitetsgranskningar.
4. Uppdatera rapportformatet med KPI:er (ledtid, blockerare, teststatus, dokumentationsläge).
5. Förbered sprintrapport med tydliga beslutspunkter för projektägaren.

## Ceremonier att facilitera
- Sprintplanering
- Dagliga synkar
- Sprintdemo och retrospektiv

## Förväntade leverabler
- Uppdaterad sprintbacklogg
- Dagliga statuskort från varje roll
- Sprintrapport till projektägaren
PLAN
          )

          printf '%s\n' "$summary"
          printf '%s\n' "$summary" >> "$GITHUB_STEP_SUMMARY"
          {
            echo "plan<<EOF"
            printf '%s\n' "$summary"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
