name: Minimal Placeholder Agent

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      plan:
        description: "Summary emitted by the placeholder agent"
        value: ${{ jobs.placeholder.outputs.plan }}

jobs:
  placeholder:
    name: Initialize placeholder agent
    runs-on: ubuntu-latest
    outputs:
      plan: ${{ steps.define_plan.outputs.plan }}
    steps:
      - name: Define agent summary
        id: define_plan
        shell: bash
        run: |
          set -euo pipefail

          objective_file="docs/agents/placeholder-objective.md"

          if [ -f "$objective_file" ]; then
            objective="$(cat "$objective_file")"
          else
            objective="Objective file '$objective_file' was not found."
          fi

          summary="# Placeholder Agent

## Objective Source
- $objective_file

## Objective
$objective

## Status
- Agent initialized successfully.
- No default actions are defined. Configure steps as needed.
"

          printf '%s\n' "$summary"

          if [ -n "${GITHUB_STEP_SUMMARY:-}" ]; then
            printf '%s\n' "$summary" >> "$GITHUB_STEP_SUMMARY"
          fi

          if [ -n "${GITHUB_OUTPUT:-}" ]; then
            {
              echo "plan<<EOF"
              printf '%s\n' "$summary"
              echo "EOF"
            } >> "$GITHUB_OUTPUT"
          fi
