name: Auto draft PR + Codex auto-fix

on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

permissions:
  contents: write
  pull-requests: write
  issues: write

env:
  TZ: Europe/Stockholm

jobs:
  issue_to_pr:
    name: Create or reuse draft PR from issue
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    env:
      REPO: ${{ github.repository }}
      ISSUE_NUMBER: ${{ github.event.issue.number }}
      ISSUE_TITLE: ${{ github.event.issue.title }}

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Determine default branch
        id: default
        run: |
          set -euo pipefail
          DEFAULT_BRANCH=$(gh repo view "$REPO" --json defaultBranchRef --jq .defaultBranchRef.name)
          echo "DEFAULT_BRANCH=$DEFAULT_BRANCH" >> $GITHUB_ENV

      - name: Find or create branch
        id: branch
        run: |
          set -euo pipefail
          PREFIX="refs/heads/codex/issue-${ISSUE_NUMBER}-*"
          EXISTING=$(git ls-remote --heads origin "$PREFIX" | awk '{print $2}' | sed 's#refs/heads/##' | head -n1 || true)
          if [[ -n "$EXISTING" ]]; then
            BRANCH="$EXISTING"
            echo "Reusing branch $BRANCH"
            git fetch origin "$BRANCH" --depth=1
            git switch -C "$BRANCH" "origin/$BRANCH"
          else
            SLUG=$(echo "$ISSUE_TITLE" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '-' | sed 's/^-//;s/-$//' | cut -c1-40)
            BRANCH="codex/issue-${ISSUE_NUMBER}${SLUG:+-$SLUG}"
            git fetch origin "$DEFAULT_BRANCH" --depth=1
            git switch -c "$BRANCH" "origin/$DEFAULT_BRANCH"
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit --allow-empty -m "Init draft for issue #${ISSUE_NUMBER}"
            git push --set-upstream origin "$BRANCH"
          fi
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV

      - name: Ensure draft PR exists
        id: pr
        run: |
          set -euo pipefail
          if gh pr view "$BRANCH" --repo "$REPO" --json number,url >/tmp/pr.json 2>/dev/null; then
            PR_NUMBER=$(jq -r .number </tmp/pr.json)
            PR_URL=$(jq -r .url </tmp/pr.json)
          else
            PR_URL=$(gh pr create \
              --base "$DEFAULT_BRANCH" \
              --head "$BRANCH" \
              --title "Draft: Issue #${ISSUE_NUMBER} – ${ISSUE_TITLE}" \
              --body "Auto-created draft PR for Issue #${ISSUE_NUMBER}\n\nCloses #${ISSUE_NUMBER}" \
              --draft \
              --repo "$REPO")
            PR_NUMBER=$(gh pr view "$BRANCH" --repo "$REPO" --json number --jq .number)
          fi
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          echo "PR_URL=$PR_URL" >> $GITHUB_ENV

      - name: Run Codex on draft PR
        uses: openai/codex-action@v1
        timeout-minutes: 20
        continue-on-error: true
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          prompt: |
            You are Codex working on branch "${{ env.BRANCH }}" for PR #${{ env.PR_NUMBER }}.
            The PR is linked to issue #${{ env.ISSUE_NUMBER }}.
            Goal:
            - Make minimal, targeted code edits to fix the issue.
            - Update docs/tests if needed.
            - Print a concise summary of what changed.

      - name: Commit and push Codex changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "Codex auto-fix for issue #${ISSUE_NUMBER}"
            git push origin "${BRANCH}"
          else
            echo "::notice::No changes from Codex."
          fi

  codex_on_pr:
    name: Run Codex on PR updates
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/head
          persist-credentials: true
          fetch-depth: 0

      - name: Run Codex for PR
        uses: openai/codex-action@v1
        timeout-minutes: 20
        continue-on-error: true
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          prompt: |
            You are Codex working directly on PR #${{ github.event.pull_request.number }}.
            This PR is linked to issue(s) via “Closes #ID” references.
            Apply any necessary edits to resolve them, update docs/tests if needed, and summarise changes.

      - name: Commit and push Codex updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "Codex auto-fix for PR #${{ github.event.pull_request.number }}"
            HEAD_REF="${{ github.head_ref }}"
            [[ -z "$HEAD_REF" ]] && HEAD_REF=$(git rev-parse --abbrev-ref HEAD)
            git push origin "$HEAD_REF"
          else
            echo "::notice::No changes from Codex."
          fi