name: Assign copilot
on:
  issues:
    types: [opened, reopened]

jobs:
  comment_and_assign:
    runs-on: ubuntu-latest
    steps:
      - name: Enable Debug Logging
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV

      - name: Comment and assign using bot token
        env:
          GH_TOKEN: ${{ secrets.BOT_ISSUE }}
        run: |
          echo "::debug::Starting API calls"
          gh api \
            repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            -f body='@copilot - Please address this issue.'
          echo "::debug::Comment added"
          gh api \
            repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
            -X PATCH \
            -f assignees='["copilot-swe-agent"]'
          echo "::debug::Assignee updated"