name: Auto create draft PR from new or reopened issue

on:
  issues:
    types: [opened, reopened]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  create_or_reuse_draft_pr:
    runs-on: ubuntu-latest
    env:
      REPO: ${{ github.repository }}
      ISSUE_NUMBER: ${{ github.event.issue.number }}
      ISSUE_TITLE: ${{ github.event.issue.title }}

    steps:
      - name: Enable Debug Logging
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV

      # Viktigt: använd inte Actions-botens credar
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Configure git user (as BOT_ISSUE owner)
        env:
          GH_TOKEN: ${{ secrets.BOT_ISSUE }}
        run: |
          set -euo pipefail
          # Hämta namn/mail för token-ägaren, om du inte vill hårdkoda dem
          NAME=$(gh api user --jq .name)
          EMAIL=$(gh api user/emails --jq 'map(select(.primary==true))[0].email' || true)
          git config user.name "${NAME:-codex-bot}"
          git config user.email "${EMAIL:-codex-bot@example.invalid}"

      - name: Determine default branch
        env:
          GH_TOKEN: ${{ secrets.BOT_ISSUE }}
        run: |
          set -euo pipefail
          DEFAULT_BRANCH=$(gh repo view "$REPO" --json defaultBranchRef --jq .defaultBranchRef.name)
          echo "DEFAULT_BRANCH=$DEFAULT_BRANCH" >> $GITHUB_ENV
          echo "::debug::Default branch is $DEFAULT_BRANCH"

      - name: Find or create branch with empty commit (using BOT_ISSUE)
        env:
          GH_TOKEN: ${{ secrets.BOT_ISSUE }}
        run: |
          set -euo pipefail

          # Bygg remote-URL med PAT så push sker som BOT_ISSUE-användaren
          git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${REPO}.git"

          EXISTING=$(git ls-remote --heads origin "refs/heads/codex/issue-${ISSUE_NUMBER}-*" | awk '{print $2}' | sed 's#refs/heads/##' | head -n1)
          if [ -n "$EXISTING" ]; then
            BRANCH="$EXISTING"
            echo "::debug::Reusing existing branch: $BRANCH"
            git fetch origin "$BRANCH" --depth=1
            git switch "$BRANCH"
          else
            SLUG=$(printf '%s' "$ISSUE_TITLE" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '-' | sed 's/^-//;s/-$//' | cut -c1-40)
            BRANCH="codex/issue-${ISSUE_NUMBER}${SLUG:+-$SLUG}"
            echo "::debug::Creating new branch: $BRANCH"
            git fetch origin "$DEFAULT_BRANCH" --depth=1
            git switch -c "$BRANCH" "origin/$DEFAULT_BRANCH"
            git commit --allow-empty -m "Init draft for issue #${ISSUE_NUMBER}"
            git push --set-upstream origin "$BRANCH"
          fi
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV

      - name: Ensure draft PR exists (create if missing) as BOT_ISSUE
        env:
          GH_TOKEN: ${{ secrets.BOT_ISSUE }}
        run: |
          set -euo pipefail
          set +e
          PR_JSON=$(gh pr view "$BRANCH" --json number,url --repo "$REPO" 2>/dev/null)
          RC=$?
          set -e
          if [ $RC -eq 0 ] && [ -n "$PR_JSON" ]; then
            PR_NUMBER=$(printf '%s' "$PR_JSON" | jq -r .number)
            PR_URL=$(printf '%s' "$PR_JSON" | jq -r .url)
            echo "::debug::Existing PR found: #$PR_NUMBER"
          else
            PR_URL=$(gh pr create \
              --base "$DEFAULT_BRANCH" \
              --head "$BRANCH" \
              --title "Draft: Issue #$ISSUE_NUMBER – $ISSUE_TITLE" \
              --body "This draft PR was auto-created for **Issue #$ISSUE_NUMBER**.

Closes #$ISSUE_NUMBER" \
              --draft \
              --repo "$REPO")
            PR_NUMBER=$(gh pr view "$BRANCH" --json number --jq .number --repo "$REPO")
            echo "::debug::Created new PR: #$PR_NUMBER"
          fi
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          echo "PR_URL=$PR_URL" >> $GITHUB_ENV

      # 💬 Kommentera som dig (PAT)
      - name: Comment on PR (ping @codex)
        env:
          GH_TOKEN: ${{ secrets.BOT_ISSUE }}
        run: |
          set -euo pipefail
          gh api repos/$REPO/issues/$PR_NUMBER/comments \
            -f body='@codex - Fix the issue using this draft PR.'
          echo "::debug::Comment added to PR #$PR_NUMBER (as personal user)"

      - name: Comment in the original issue (link to PR and ping @codex)
        env:
          GH_TOKEN: ${{ secrets.BOT_ISSUE }}
        run: |
          set -euo pipefail
          gh api repos/$REPO/issues/$ISSUE_NUMBER/comments \
            -f body="A draft PR has been created or reused for this issue: ${PR_URL}

@codex - please take a look."
          echo "::debug::Comment added to Issue #$ISSUE_NUMBER (as personal user)"