name: Manual text to multiple GitHub issues (British English)

on:
  workflow_dispatch:
    inputs:
      source_text:
        description: "Paste your backlog text here (free-form)."
        required: true
        default: ""
      dry_run:
        description: "Preview only (true/false). Default: true"
        required: true
        default: ""

permissions:
  contents: read
  issues: write

jobs:
  create_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Ensure tools
        run: |
          set -euo pipefail
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Make script executable
        run: chmod +x .github/scripts/generate_issues.sh

      - name: Generate (and optionally create) issues
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SOURCE_TEXT: ${{ github.event.inputs.source_text }}
          DRY_RUN: ${{ github.event.inputs.dry_run }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: .github/scripts/generate_issues.sh