name: Auto Codex for Issues + PRs (create PR if missing)

on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.issue.number || github.ref }}
  cancel-in-progress: false

jobs:
  # ============================================================
  # JOB 0 – Issue: create or reuse branch and ensure draft PR
  # ============================================================
  issue_create_draft_pr:
    # if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.setvars.outputs.branch }}
      pr_number: ${{ steps.setvars.outputs.pr_number }}
      pr_url: ${{ steps.setvars.outputs.pr_url }}
    env:
      REPO: ${{ github.repository }}
      ISSUE_NUMBER: ${{ github.event.issue.number }}
      ISSUE_TITLE: ${{ github.event.issue.title }}
    steps:
      - name: Enable debug logging
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Determine default branch
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          DEFAULT_BRANCH=$(gh repo view "$REPO" --json defaultBranchRef --jq .defaultBranchRef.name)
          echo "DEFAULT_BRANCH=$DEFAULT_BRANCH" >> $GITHUB_ENV

      - name: Find or create branch with empty commit
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          PREFIX="refs/heads/codex/issue-${ISSUE_NUMBER}-*"
          EXISTING=$(git ls-remote --heads origin "$PREFIX" \
            | awk '{print $2}' | sed 's#refs/heads/##' | head -n1 || true)

          if [[ -n "${EXISTING:-}" ]]; then
            BRANCH="$EXISTING"
            echo "::debug::Reusing existing branch: $BRANCH"
            git fetch origin "$BRANCH" --depth=1
            git switch -C "$BRANCH" "origin/$BRANCH"
          else
            SLUG=$(printf '%s' "$ISSUE_TITLE" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '-' | sed 's/^-//;s/-$//' | cut -c1-40)
            BRANCH="codex/issue-${ISSUE_NUMBER}${SLUG:+-$SLUG}"
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git fetch origin "$DEFAULT_BRANCH" --depth=1
            git switch -c "$BRANCH" "origin/$DEFAULT_BRANCH"
            git commit --allow-empty -m "Initial draft for issue #${ISSUE_NUMBER}"
            git push --set-upstream origin "$BRANCH"
          fi
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV

      - name: Ensure draft PR exists (create if missing)
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          set +e
          PR_JSON=$(gh pr view "$BRANCH" --json number,url --repo "$REPO" 2>/dev/null)
          RC=$?
          set -e
          if [ $RC -eq 0 ] && [ -n "$PR_JSON" ]; then
            PR_NUMBER=$(echo "$PR_JSON" | jq -r .number)
            PR_URL=$(echo "$PR_JSON" | jq -r .url)
          else
            PR_URL=$(gh pr create \
              --base "$DEFAULT_BRANCH" \
              --head "$BRANCH" \
              --title "Draft: Issue #$ISSUE_NUMBER – $ISSUE_TITLE" \
              --body "This draft pull request was automatically created for this issue.

              Closes #$ISSUE_NUMBER" \
              --draft \
              --repo "$REPO")
            PR_NUMBER=$(gh pr view "$BRANCH" --json number --jq .number --repo "$REPO")
          fi
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          echo "PR_URL=$PR_URL" >> $GITHUB_ENV

      - name: Set job outputs
        id: setvars
        run: |
          echo "branch=${BRANCH}" >> $GITHUB_OUTPUT
          echo "pr_number=${PR_NUMBER}" >> $GITHUB_OUTPUT
          echo "pr_url=${PR_URL}" >> $GITHUB_OUTPUT
          echo "::notice::Draft PR ensured: ${PR_URL} (#${PR_NUMBER}) on branch ${BRANCH}"

  # ============================================================
  # JOB 1 – Issue: run Codex on the draft PR created above
  # ============================================================
  issue_codex:
    if: github.event_name == 'issues'
    needs: issue_create_draft_pr
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ needs.issue_create_draft_pr.outputs.branch }}
      PR_NUMBER: ${{ needs.issue_create_draft_pr.outputs.pr_number }}
      REPO: ${{ github.repository }}
      ISSUE_NUMBER: ${{ github.event.issue.number }}
    steps:
      - name: Check out PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}
          persist-credentials: true

      - name: Retrieve PR metadata
        id: prsha
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          pr=$(gh pr view "$PR_NUMBER" --json headRefOid,baseRefOid,title,body)
          echo "base_sha=$(echo "$pr" | jq -r .baseRefOid)" >> "$GITHUB_OUTPUT"
          echo "head_sha=$(echo "$pr" | jq -r .headRefOid)" >> "$GITHUB_OUTPUT"
          echo "pr_title=$(echo "$pr" | jq -r .title)" >> "$GITHUB_OUTPUT"
          {
            echo "pr_body<<EOF"
            echo "$(echo "$pr" | jq -r .body)"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Detect linked issues (fallback to current issue)
        id: linked_issue
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
          OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ env.PR_NUMBER }}
          ISSUE_NUMBER: ${{ env.ISSUE_NUMBER }}
        run: |
          set -euo pipefail
          q='query($owner:String!,$repo:String!,$number:Int!){
            repository(owner:$owner,name:$repo){
              pullRequest(number:$number){
                closingIssuesReferences(first:10){nodes{number title}}
              }
            }
          }'
          nums=""
          for i in 1 2 3; do
            data=$(gh api graphql -f query="$q" -F owner="$OWNER" -F repo="$REPO_NAME" -F number="$PR_NUMBER" || true)
            nums=$(echo "$data" | jq -r '.data.repository.pullRequest.closingIssuesReferences.nodes|map(.number)|join(",")' 2>/dev/null || true)
            [[ -n "$nums" ]] && break || sleep 2
          done
          [[ -z "$nums" ]] && nums="$ISSUE_NUMBER"
          echo "numbers=$nums" >> $GITHUB_OUTPUT

      - name: Run Codex on PR branch (with write permissions)
        id: run_codex_issue
        uses: openai/codex-action@v1
        timeout-minutes: 10
        continue-on-error: true
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          prompt: |
            You are Codex working on branch "${{ env.BRANCH }}" for PR #${{ env.PR_NUMBER }}.
            The PR is linked to issue(s) #${{ steps.linked_issue.outputs.numbers }}.

            Make minimal and targeted code changes to resolve the linked issue(s).
            Update any related tests or documentation where appropriate.
            At the end, print a concise summary of what was changed.

            Context:
            - Base SHA: ${{ steps.prsha.outputs.base_sha }}
            - Head SHA: ${{ steps.prsha.outputs.head_sha }}
            - PR title: ${{ steps.prsha.outputs.pr_title }}
            - PR body:
            ${{ steps.prsha.outputs.pr_body }}

      - name: Commit and push Codex changes
        shell: bash
        run: |
          set -euo pipefail
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "Codex auto-fix for issue(s) #${{ steps.linked_issue.outputs.numbers }}"
            git push origin "${BRANCH}"
            echo "::notice::Committed and pushed Codex changes to ${BRANCH}"
          else
            echo "::notice::No file changes to commit."
          fi

  # ============================================================
  # JOB 2 – PR: run Codex when PR events occur
  # ============================================================
  pr_codex:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Check out PR head branch
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/head
          persist-credentials: true

      - name: Detect linked issues
        id: linked
        env:
          GH_TOKEN: ${{ github.token }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          q='query($owner:String!,$repo:String!,$number:Int!){
            repository(owner:$owner,name:$repo){
              pullRequest(number:$number){
                closingIssuesReferences(first:10){nodes{number title}}
              }
            }
          }'
          data=$(gh api graphql -f query="$q" -F owner="$OWNER" -F repo="$REPO" -F number="$PR_NUMBER")
          nums=$(echo "$data" | jq -r '.data.repository.pullRequest.closingIssuesReferences.nodes|map(.number)|join(",")')
          if [[ -n "$nums" ]]; then
            echo "has=true" >> $GITHUB_OUTPUT
            echo "numbers=$nums" >> $GITHUB_OUTPUT
          else
            echo "has=false" >> $GITHUB_OUTPUT
          fi

      - name: Skip if PR has no linked issues
        if: steps.linked.outputs.has != 'true'
        run: echo "No linked issues → skipping Codex run."

      - name: Run Codex on PR branch
        if: steps.linked.outputs.has == 'true'
        id: run_codex_pr
        uses: openai/codex-action@v1
        timeout-minutes: 10
        continue-on-error: true
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          prompt: |
            You are Codex working directly on the pull request head branch (#${{ github.event.pull_request.number }}).
            The PR is linked to issue(s) #${{ steps.linked.outputs.numbers }}.

            Make the necessary code edits directly in the workspace to resolve those issues.
            Update tests and documentation if required, then print a concise summary.

            Context:
            - Base SHA: ${{ github.event.pull_request.base.sha }}
            - Head SHA: ${{ github.event.pull_request.head.sha }}

      - name: Commit and push Codex changes
        if: steps.linked.outputs.has == 'true'
        shell: bash
        run: |
          set -euo pipefail
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "Codex auto-fix for issue(s) #${{ steps.linked.outputs.numbers }}"
            HEAD_REF="${{ github.head_ref }}"
            [[ -z "$HEAD_REF" ]] && HEAD_REF=$(git rev-parse --abbrev-ref HEAD)
            git push origin "$HEAD_REF"
            echo "::notice::Committed and pushed Codex changes to ${HEAD_REF}"
          else
            echo "::notice::No file changes to commit."
          fi