# .github/workflows/example-producer.yml
name: Example Producer

on:
  workflow_dispatch:

jobs:
  enqueue_something:
    uses: Geonitab/Actions-que/.github/workflows/enqueue-task.yml@main
    with:
      queue_issue_number: 1
      task: "Generate glossary relations for term: 'Terraform state' (limit 20)"
      correlation_id: "archbook-TERMS-001"