---
name: Build MkDocs Site

on:
  push:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
  pull_request:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
  workflow_dispatch: # Tillåter manuell körning av arbetsflödet

permissions:
  contents: write

jobs:
  build:
    name: Build documentation site
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install MkDocs
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs pymdown-extensions

      - name: Build MkDocs site
        run: mkdocs build

      - name: Prepare static site artifacts
        run: |
          if [ -f CNAME ]; then
            cp CNAME site/CNAME
          fi
          touch site/.nojekyll

      - name: Deploy MkDocs site to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git fetch
          git switch -C gh-pages
          git rm -rf . || true
          cp -r site/. .
          git add .
          if git diff --cached --quiet; then
            echo "No changes to deploy"
            exit 0
          fi
          git commit -m "Deploy MkDocs site"
          git push origin gh-pages --force
