name: Close issues on push to main

on:
  push:
    branches:
      - main

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Close issues mentioned in commit messages
        uses: actions/github-script@v7
        with:
          script: |
            const commits = context.payload.commits;
            const issueRegex = /(close[sd]?|fix(e[sd])?|resolve[sd]?)\s+#(\d+)/gi;

            for (const commit of commits) {
              let match;
              while ((match = issueRegex.exec(commit.message)) !== null) {
                const issue_number = parseInt(match[3]);
                console.log(`🔹 Found issue #${issue_number} in commit: ${commit.id}`);

                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number,
                  state: 'closed',
                });

                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number,
                  body: `✅ Automatically closed because the fix was pushed to \`main\` in commit \`${commit.id}\`.`
                });
              }
            }