name: Cleanup Old Branches

on:
  schedule:
    - cron: "0 3 * * *"  # Runs every day at 03:00 UTC
  workflow_dispatch:      # Allow manual run

jobs:
  cleanup:
    runs-on: ubuntu-latest

    permissions:
      contents: write    # Needed to delete branches via GitHub API

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete branches older than 2 days (except main & gh-pages)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching all remote branches..."
          git fetch --prune

          # Get all branches except main and gh-pages
          for branch in $(git for-each-ref --format='%(refname:short)' refs/remotes/origin/ | grep -vE '^(main|gh-pages)$'); do
            branch_name=$(echo $branch | sed 's|origin/||')

            # Get last commit date (ISO format)
            last_commit_date=$(git log -1 --format=%ci origin/$branch_name)
            last_commit_epoch=$(date -d "$last_commit_date" +%s)
            now_epoch=$(date +%s)
            age_days=$(( (now_epoch - last_commit_epoch) / 86400 ))

            if [ $age_days -ge 2 ]; then
              echo "🗑️ Deleting branch '$branch_name' (last commit $age_days days ago)..."
              git push origin --delete "$branch_name"
            else
              echo "✅ Keeping branch '$branch_name' (last commit $age_days days ago)"
            fi
          done