name: Close conflicted pull requests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  workflow_dispatch: # Allow manual triggering of the workflow.

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  close-conflicts:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Ensure compatibility with @actions/core and github-script.

      - name: Install Missing Dependency
        run: npm install @actions/core

      - name: Await mergeability assessment
        id: mergeability
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            {
              const core = require('@actions/core');
              const prNumber = context.payload.pull_request.number;
              let pr;

              for (let attempt = 0; attempt < 6; attempt += 1) {
                ({ data: pr } = await github.rest.pulls.get({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: prNumber,
                }));

                if (pr.mergeable !== null) {
                  break;
                }

                core.info('Mergeability is currently unknown, waiting before retrying.');
                await new Promise((resolve) => setTimeout(resolve, 5000));
              }

              const hasConflicts = pr.mergeable === false && pr.mergeable_state === 'dirty';
              core.setOutput('mergeable', pr.mergeable === null ? 'unknown' : String(pr.mergeable));
              core.setOutput('mergeable_state', pr.mergeable_state ?? 'unknown');
              core.setOutput('has_conflicts', hasConflicts ? 'true' : 'false');
            }