name: Close conflicted pull requests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  workflow_dispatch: # Allow manual triggering of the workflow.

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  close-conflicts:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Ensure compatibility with @actions/core and github-script.

      - name: Install Missing Dependency
        run: npm install @actions/core

      - name: Check PR Status
        id: pr-status
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            {
              const core = require('@actions/core');
              const prNumber = context.payload.pull_request.number;
              let pr;

              for (let attempt = 0; attempt < 6; attempt += 1) {
                ({ data: pr } = await github.rest.pulls.get({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: prNumber,
                }));

                if (pr.mergeable !== null) {
                  break;
                }

                core.info('Mergeability is currently unknown, waiting before retrying.');
                await new Promise((resolve) => setTimeout(resolve, 5000));
              }

              const hasConflicts = pr.mergeable === false && pr.mergeable_state === 'dirty';
              const noFilesChanged = pr.changed_files === 0;

              core.setOutput('has_conflicts', hasConflicts ? 'true' : 'false');
              core.setOutput('no_files_changed', noFilesChanged ? 'true' : 'false');

              if (hasConflicts || noFilesChanged) {
                const reason = hasConflicts
                  ? 'merge conflicts'
                  : 'no files being changed';
                const issueTitle = `Pull Request #${prNumber} closed: ${reason}`;
                const issueBody = `Pull request #${prNumber} was closed due to ${reason}.\n\nPull Request Link: ${pr.html_url}`;

                // Create an issue to report the reason for closure
                const { data: issue } = await github.rest.issues.create({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  title: issueTitle,
                  body: issueBody,
                });

                core.info(`Created issue #${issue.number} to report pull request closure reason.`);

                // Close the pull request
                await github.rest.pulls.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: prNumber,
                  state: 'closed',
                });

                core.info(`Closed pull request #${prNumber} due to ${reason}.`);
              }
            }