name: Create GitHub Issues from Markdown

on:
  workflow_dispatch:  # Manual trigger

jobs:
  create_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python environment
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install required packages
        run: pip install requests

      - name: Execute issue creation script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: python .github/scripts/create_issues.py
