name: delay

on: 
  workflow_dispatch: {}
  workflow_call: {}

jobs:
  random-wait-job:
    runs-on: ubuntu-latest
    steps:
      - name: Random delay before execution
        run: |
          DELAY=$((RANDOM % 601))
          echo "Sleeping for $DELAY seconds..."
          sleep "$DELAY"
          echo "Done waiting, continuing."