name: Dependabot auto-merge

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      
    - name: Install dependencies
      run: |
        echo "Install dependencies here"
      
    - name: Run auto-merge
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Run your auto-merge command here"