name: Editor Bot - Auto PR

on:
  issues:
    types:
      - opened
      - labeled
      - reopened

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  prepare_documentation_pr:
    if: >-
      contains(github.event.issue.labels.*.name, 'documentation') ||
      contains(github.event.issue.labels.*.name, 'Documentation') ||
      contains(github.event.issue.labels.*.name, 'DOCUMENTATION') ||
      (github.event.label != null &&
       contains(fromJSON('["documentation","Documentation","DOCUMENTATION"]'), github.event.label.name))
    runs-on: ubuntu-latest
    steps:
      - name: Wait for issue response labeling
        run: sleep 15

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate documentation response
        run: python scripts/editor_bot.py
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Create documentation response pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: editor/issue-${{ github.event.issue.number }}
          base: ${{ github.event.repository.default_branch }}
          title: "Add documentation plan for issue #${{ github.event.issue.number }}"
          commit-message: "Add documentation plan for issue #${{ github.event.issue.number }}"
          labels: documentation
          body: |
            ## Summary
            - Automatically generated documentation response for #${{ github.event.issue.number }}
            - Review the outline and expand the documentation content as needed.

            Fixes #${{ github.event.issue.number }}
          add-paths: |
            docs/documentation/**
