name: Issue Responder AI Agent

on:
  issues:
    types: [opened, reopened]

permissions:
  issues: write

jobs:
  respond_to_latest_issue:
    name: Respond to latest issue
    runs-on: ubuntu-latest
    steps:
      - name: Thank user for latest issue
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const { data: issues } = await github.rest.issues.listForRepo({
              owner,
              repo,
              state: 'all',
              sort: 'created',
              direction: 'desc',
              per_page: 1,
            });

            if (!issues.length) {
              core.info('No issues found to respond to.');
              return;
            }

            const latestIssue = issues[0];

            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: latestIssue.number,
              body: 'Thank you for posting an issue',
            });

            core.info(`Responded to issue #${latestIssue.number}.`);
