name: Auto-assign to Copilot

on:
  issues:
    types: [opened, reopened]

jobs:
  assign-copilot:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Assign to Copilot
        uses: otto-de/assign_issue_toCopilot_action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 