name: Issue Response

on:
  issues:
    types: [opened]  # Triggers on new issues

jobs:
  greet:
    runs-on: ubuntu-latest
    permissions:
      issues: write  # Required to assign assignees and comment
      pull-requests: write
    steps:
      - name: Welcome new issue
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Thanks for opening this issue! Assigning Copilot."
            })

      # NEW STEP: Automatic assignment to Copilot
      - name: Assign to Copilot
        run: |
          gh issue edit ${{ github.event.issue.number }} --add-assignee Copilot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Used automatically for authentication

      # Optional: Add labels or other actions here