name: Issue Responder AI Agent

on:
  issues:
    types: [opened, reopened]

permissions:
  issues: write

jobs:
  respond_to_latest_issue:
    name: Respond to latest issue
    runs-on: ubuntu-latest
    steps:
      - name: Assign best-fit bot to latest issue
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const fs = require('fs');
            const path = require('path');

            const { data: issues } = await github.rest.issues.listForRepo({
              owner,
              repo,
              state: 'all',
              sort: 'created',
              direction: 'desc',
              per_page: 1,
            });

            if (!issues.length) {
              core.info('No issues found to respond to.');
              return;
            }

            const latestIssue = issues[0];

            const content = `${latestIssue.title} ${latestIssue.body || ''}`.toLowerCase();

            const botAssignments = [
              { name: 'Designer', keywords: ['ui', 'ux', 'visual', 'styling', 'layout', 'mockup', 'branding'] },
              { name: 'Architect', keywords: ['architecture', 'architectural', 'blueprint', 'system layout', 'system map', 'infrastructure'] },
              { name: 'Quality Assurance', keywords: ['bug', 'issue', 'error', 'test', 'testing', 'qa', 'quality', 'failure'] },
              { name: 'Developer', keywords: ['develop', 'development', 'implement', 'implementation', 'code', 'coding', 'feature', 'fix'] },
              { name: 'Documentarian', keywords: ['documentation', 'document', 'docs', 'guide', 'manual', 'readme'] },
              { name: 'Requirements Analyst', keywords: ['requirement', 'requirements', 'analysis', 'specification', 'user story', 'acceptance criteria'] },
              { name: 'Editor', keywords: ['edit', 'editing', 'copy', 'proofread', 'language', 'grammar', 'tone'] },
            ];

            const assignedBot = botAssignments.find(({ keywords }) =>
              keywords.some((keyword) => content.includes(keyword))
            )?.name || 'Requirements Analyst';

            const templatesDir = path.join(process.env.GITHUB_WORKSPACE, '.github', 'issue-response');
            const slugify = (value) => value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
            const templatePaths = [
              path.join(templatesDir, `${slugify(assignedBot)}.tml`),
              path.join(templatesDir, 'issue-response.tml'),
            ];

            let commentTemplate = `Hello! After reviewing this issue, the ${assignedBot} bot will take the lead. They will follow up with the next steps shortly.`;

            for (const templatePath of templatePaths) {
              if (fs.existsSync(templatePath)) {
                commentTemplate = fs.readFileSync(templatePath, 'utf8');
                break;
              }
            }

            const commentBody = commentTemplate
              .replace(/{{\s*bot_name\s*}}/gi, assignedBot)
              .replace(/{{\s*issue_title\s*}}/gi, (latestIssue.title || '').trim())
              .replace(/{{\s*issue_number\s*}}/gi, latestIssue.number);

            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: latestIssue.number,
              body: commentBody,
            });

            core.info(`Assigned ${assignedBot} bot to issue #${latestIssue.number}.`);
