name: Ready eligible draft PRs

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  ready-eligible-drafts:
    runs-on: ubuntu-latest
    steps:
      - name: Mark only draft PRs that have file changes as Ready for review
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
        run: |
          echo "Scanning open draft PRs in $REPO ..."
          # Get all open draft PR numbers
          mapfile -t PRS < <(gh pr list --repo "$REPO" --state open --json number,isDraft --jq '.[] | select(.isDraft==true) | .number')

          if [ ${#PRS[@]} -eq 0 ]; then
            echo "No open draft PRs found."
            echo "No open draft PRs found." >> "$GITHUB_STEP_SUMMARY"
            exit 0
          fi

          echo "## Results" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "| PR | Title | Changed files | Commits | Action |" >> "$GITHUB_STEP_SUMMARY"
          echo "|---:|-------|---------------:|--------:|--------|" >> "$GITHUB_STEP_SUMMARY"

          for pr in "${PRS[@]}"; do
            info="$(gh pr view "$pr" --repo "$REPO" --json number,title,changedFiles,commits,isDraft)"
            title="$(jq -r '.title' <<< "$info")"
            changed_files="$(jq -r '.changedFiles' <<< "$info")"
            commit_count="$(jq -r '.commits' <<< "$info")"

            if [ "$changed_files" -gt 0 ] && [ "$commit_count" -gt 0 ]; then
              if gh pr ready "$pr" --repo "$REPO"; then
                action="✅ Marked ready"
              else
                action="❌ Failed to mark"
              fi
            else
              action="⏭️ Skipped (no files/commits)"
            fi

            echo "| #$pr | ${title//|/-} | $changed_files | $commit_count | $action |" >> "$GITHUB_STEP_SUMMARY"
          done