name: Requirements Bot - Auto PR

on:
  issues:
    types:
      - opened
      - labeled
      - reopened

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  prepare_requirements_pr:
    if: >-
      contains(github.event.issue.labels.*.name, 'Req') ||
      contains(github.event.issue.labels.*.name, 'req') ||
      contains(github.event.issue.labels.*.name, 'REQ') ||
      (github.event.label != null &&
       contains(fromJSON('["Req","req","REQ"]'), github.event.label.name))
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate requirements response
        run: python scripts/requirements_bot.py
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Create requirements response pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: requirements/issue-${{ github.event.issue.number }}
          base: ${{ github.event.repository.default_branch }}
          title: "Add requirements plan for issue #${{ github.event.issue.number }}"
          commit-message: "Add requirements plan for issue #${{ github.event.issue.number }}"
          labels: Req
          body: |
            ## Summary
            - Automatically generated requirements response for #${{ github.event.issue.number }}
            - Review the inventory, traceability, and acceptance criteria before execution.

            Fixes #${{ github.event.issue.number }}
          add-paths: |
            docs/requirements/**
