name: Translate Codebase to Swedish

on:
  workflow_dispatch:

jobs:
  translate-and-commit:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U translators

      - name: Run translation script
        # Uppdaterad sökväg till skriptet
        run: python scripts/translate_repo.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          git add .
          
          if git diff-index --quiet HEAD; then
            echo "Inga ändringar att committa."
          else
            git commit -m "chore: Automatiskt översatt filer till svenska"
            git push
          fi
