name: Build Whitepapers (native)

on:
  push:
    branches: [ main ]
    paths:
      - 'whitepapers/**/*'
      - 'templates/**/*'
      - 'generate_whitepapers.py'
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}
  workflow_call: {}

permissions:
  contents: read

env:
  ARTIFACT_RETENTION_DAYS: 30

jobs:
  whitepapers:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Python deps (if any)
        if: ${{ hashFiles('requirements.txt') != '' }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Pandoc & TeX toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            pandoc \
            texlive-xetex texlive-fonts-recommended texlive-latex-extra \
            librsvg2-bin graphviz

      - name: Generate whitepapers
        run: |
          mkdir -p releases/whitepapers
          python3 generate_whitepapers.py --release || python3 generate_whitepapers.py

      - name: Upload whitepaper artefacts
        uses: actions/upload-artifact@v4
        with:
          name: whitepapers
          path: releases/whitepapers/
          retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}
          if-no-files-found: warn
